Le_Domain='te.gregsmarty.co.uk'
Le_Alt='no'
Le_Webroot='no'
Le_PreHook=''
Le_PostHook=''
Le_RenewHook=''
Le_API='https://acme-v02.api.letsencrypt.org/directory'
Le_RealCertPath=''
Le_RealCACertPath=''
Le_RealKeyPath='/etc/xray/xray.key'
Le_ReloadCmd=''
Le_RealFullChainPath='/etc/xray/xray.crt'
Le_Keylength='ec-256'
Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/3599448241/540837761161'
Le_LinkOrder='https://acme-v02.api.letsencrypt.org/acme/order/3599448241/540837761161'
Le_LinkCert='https://acme-v02.api.letsencrypt.org/acme/cert/0512faad726b9fef400f8236be069d31010e'
Le_CertCreateTime='1785876332'
Le_CertCreateTimeStr='2026-08-04T20:45:32Z'
Le_NextRenewTimeStr='2026-10-03T17:03:16Z'
Le_NextRenewTime='1791046996'
Le_InstallCertSuccessTime='1785876333'
Le_InstallCertSuccessTimeStr='2026-08-04T20:45:33Z'
